name: Jobs Paralelos

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Job 1: Análise de código
  code-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Análise de sintaxe
      run: |
        echo "Analisando sintaxe do código..."
        sleep 3
        echo "Análise de sintaxe concluída"
    
    - name: Verificar padrões de código
      run: |
        echo "Verificando padrões de código..."
        sleep 2
        echo "Padrões verificados"
    
    - name: Upload relatório análise
      run: |
        echo "Fazendo upload do relatório..."
        echo "Relatório de análise gerado em $(date)" > analysis-report.txt
        echo "Relatório salvo"

  # Job 2: Testes unitários (executa em paralelo com code-analysis)
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar ambiente de testes
      run: |
        echo "Configurando ambiente de testes..."
        sleep 2
        echo "Ambiente configurado"
    
    - name: Executar testes unitários
      run: |
        echo "Executando testes unitários..."
        sleep 4
        echo "Todos os testes passaram (15/15)"
    
    - name: Gerar relatório de cobertura
      run: |
        echo "Gerando relatório de cobertura..."
        sleep 1
        echo "Cobertura: 85%"

  # Job 3: Build da aplicação (executa em paralelo)
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Configurar ambiente de build
      run: |
        echo "Configurando ambiente de build..."
        sleep 2
        echo "Ambiente configurado"
    
    - name: Compilar aplicação
      run: |
        echo "Compilando aplicação..."
        sleep 5
        echo "Build concluído com sucesso"
    
    - name: Gerar artefatos
      run: |
        echo "Gerando artefatos..."
        mkdir -p build
        echo "Aplicação compilada em $(date)" > build/app.jar
        echo "Artefatos gerados"
    
    - name: Upload artefatos
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/