on:
  schedule:
    # Executa as 21:51 horario brasilia (UTC)
    - cron: '55 00 * * *'
  workflow_dispatch:

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
    
    - name: Informações do Schedule
      run: |
        echo "Workflow disparado por SCHEDULE"
        echo "Data atual: $(date)"
        echo "Hora UTC: $(date -u)"
        echo "Timezone: $(date +%Z)"
    
    - name: Relatório diário automatizado
      run: |
        echo "RELATÓRIO DIÁRIO AUTOMATIZADO"
        echo "================================"
        echo "Total de commits: $(git rev-list --all --count)"
        echo "Contribuidores únicos: $(git shortlog -sn | wc -l)"
        echo "Último commit: $(git log -1 --pretty=format:'%h - %s (%an, %ar)')"

