name: Logs, Debug e Problem Matchers

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Gerar Step Summary
        shell: bash
        run: |
          echo "# Resumo do Job" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "Este resumo foi gerado durante a execução do job." >> "$GITHUB_STEP_SUMMARY"
          echo "- Status esperado: OK" >> "$GITHUB_STEP_SUMMARY"

      - name: Registrar problem matcher simples (conceitual)
        run: echo "::add-matcher::.github/problem-matchers/demo.json"

      - name: Emitir mensagem que casa com o matcher
        run: |
          echo "ERROR: arquivo app/main.py na linha 42 com erro de sintaxe"

      - name: Mensagens de log úteis
        run: |
          echo "::group::Bloco de logs agrupados"
          echo "Linha 1 de logs"
          echo "Linha 2 de logs"
          echo "::endgroup::"
          echo "::warning title=Aviso::Exemplo de aviso padronizado"
          echo "::error title=Erro::Exemplo de erro padronizado"

      - name: Remover problem matcher (limpeza)
        if: always()
        run: echo "::remove-matcher owner=demo"

      - name: Finalização
        run: echo "Pipeline executado com sucesso (verifique anotações e resumo)."